BEGIN;

-- Додаткові актуальні заявки за останні 3 дні: 15 PENDING та 10 IN_PROGRESS
-- Для PENDING події комунікації та зміни статусу ще не створюються.
-- Для IN_PROGRESS створюється одна подія переходу PENDING -> IN_PROGRESS.
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Yana', 'Шевченко', '+380670000199', 'applicant199@example.com', 'Цікавиться форматом навчання.', 8, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-16 09:20:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Олена', 'Сидоренко', '+380670000200', 'applicant200@example.com', 'Просить надіслати деталі на email.', 1, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-16 11:45:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Артем', 'Федоренко', '+380670000201', 'applicant201@example.com', 'Потрібно узгодити зручний час дзвінка.', 2, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-16 15:10:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Анна', 'Мельник', '+380670000202', 'applicant202@example.com', 'Уточнює графік занять.', 3, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-16 18:35:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Богдан', 'Романенко', '+380670000203', 'applicant203@example.com', 'Потрібна додаткова консультація щодо програми.', 4, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-16 20:05:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Diana', 'Левченко', '+380670000204', 'applicant204@example.com', NULL, 5, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-17 08:50:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Вікторія', 'Петренко', '+380670000205', 'applicant205@example.com', 'Цікавиться форматом навчання.', 6, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-17 10:25:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Єгор', 'Кравченко', '+380670000206', 'applicant206@example.com', 'Просить надіслати деталі на email.', 7, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-17 13:40:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Sasha', 'Гриценко', '+380670000207', 'applicant207@example.com', 'Потрібно узгодити зручний час дзвінка.', 8, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-17 16:15:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Дарина', 'Коваленко', '+380670000208', 'applicant208@example.com', 'Уточнює графік занять.', 1, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-17 21:30:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Іван', 'Ткаченко', '+380670000209', 'applicant209@example.com', 'Потрібна додаткова консультація щодо програми.', 2, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-18 09:05:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Дмитро', 'Павленко', '+380670000210', 'applicant210@example.com', NULL, 3, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-18 10:55:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Юлія', 'Савченко', '+380670000211', 'applicant211@example.com', 'Цікавиться форматом навчання.', 4, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-18 12:35:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Nazar', 'Бондаренко', '+380670000212', 'applicant212@example.com', 'Просить надіслати деталі на email.', 5, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-18 14:20:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Marta', 'Мороз', '+380670000213', 'applicant213@example.com', 'Потрібно узгодити зручний час дзвінка.', 6, (SELECT status_id FROM application_status WHERE name = 'PENDING'), '2026-05-18 17:45:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Поліна', 'Захарченко', '+380670000214', 'applicant214@example.com', 'Уточнює графік занять.', 7, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-16 10:15:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant214@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-16 16:03:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Timur', 'Шевченко', '+380670000215', 'applicant215@example.com', 'Потрібна додаткова консультація щодо програми.', 8, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-16 12:30:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant215@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-16 18:35:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Владислав', 'Сидоренко', '+380670000216', 'applicant216@example.com', NULL, 1, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-16 17:55:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant216@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-16 19:07:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Марія', 'Федоренко', '+380670000217', 'applicant217@example.com', 'Цікавиться форматом навчання.', 2, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-17 09:35:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant217@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-17 11:54:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Софія', 'Мельник', '+380670000218', 'applicant218@example.com', 'Просить надіслати деталі на email.', 3, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-17 11:20:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant218@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-17 14:46:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Максим', 'Романенко', '+380670000219', 'applicant219@example.com', 'Потрібно узгодити зручний час дзвінка.', 4, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-17 18:10:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant219@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-17 22:43:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Катерина', 'Левченко', '+380670000220', 'applicant220@example.com', 'Уточнює графік занять.', 5, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-18 08:40:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant220@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-18 14:20:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Roman', 'Петренко', '+380670000221', 'applicant221@example.com', 'Потрібна додаткова консультація щодо програми.', 6, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-18 11:50:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant221@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-18 18:37:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Андрій', 'Кравченко', '+380670000222', 'applicant222@example.com', NULL, 7, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-18 15:05:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant222@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-18 16:09:00+03');
INSERT INTO application (first_name, last_name, phone, email, comment, program_id, status_id, datetime) VALUES ('Lisa', 'Гриценко', '+380670000223', 'applicant223@example.com', 'Цікавиться форматом навчання.', 8, (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), '2026-05-18 19:25:00+03');
INSERT INTO application_status_change (application_id, previous_status_id, new_status_id, reason, datetime) VALUES ((SELECT application_id FROM application WHERE email = 'applicant223@example.com'), (SELECT status_id FROM application_status WHERE name = 'PENDING'), (SELECT status_id FROM application_status WHERE name = 'IN_PROGRESS'), 'Заявку взято в опрацювання', '2026-05-18 21:36:00+03');
COMMIT;
